name: Get Cass Projects

on:
  workflow_dispatch:
  schedule:
    - cron: "6 0 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    outputs:
          has-changes: ${{ steps.check-for-changes.outputs.has-changes }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Run script
      run: python ./_explore/scripts/get_cass_projects.py
  
    - name: Check for changes to input_lists.json
      id: check-for-changes
      run: |
        if git diff --exit-code _explore/input_lists.json; then
          echo "No changes to commit."
          echo "has-changes=false" >> $GITHUB_OUTPUT
        else
          echo "There are changes."
          echo "has-changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: ${{ steps.check-for-changes.outputs.has-changes == true }}
        echo "Commit changes."

      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Committing new products found in CASS _software'

